export const users = [
  {
    id: 1,
    name: "John Doe",
    status: "Active",
    rating: 4,
    email: "john@example.com",
    phone: "9876543210",
    posts: 12,
    profilePicture: "/src/assets/user.svg",
  },
  {
    id: 2,
    name: "Jane Smith",
    status: "Blocked",
    rating: 3,
    email: "jane@example.com",
    phone: "9876543211",
    posts: 8,
    profilePicture: "/src/assets/user.svg",
  },
  {
    id: 3,
    name: "Alice Johnson",
    status: "Active",
    rating: 5,
    email: "alice@example.com",
    phone: "9876543212",
    posts: 15,
    profilePicture: "/src/assets/user.svg",
  },
  {
    id: 4,
    name: "Bob Lee",
    status: "Active",
    rating: 2,
    email: "bob@example.com",
    phone: "9876543213",
    posts: 3,
    profilePicture: "/src/assets/user.svg",
  },
  {
    id: 5,
    name: "Sara Khan",
    status: "Blocked",
    rating: 4,
    email: "sara@example.com",
    phone: "9876543214",
    posts: 9,
    profilePicture: "/src/assets/user.svg",
  },
  {
    id: 6,
    name: "David Miller",
    status: "Active",
    rating: 5,
    email: "david@example.com",
    phone: "9876543215",
    posts: 17,
    profilePicture: "/src/assets/user.svg",
  },
  {
    id: 7,
    name: "Emma Watson",
    status: "Active",
    rating: 3,
    email: "emma@example.com",
    phone: "9876543216",
    posts: 11,
    profilePicture: "/src/assets/user.svg",
  },
    {
    id: 8,
    name: "Emma Watson",
    status: "Active",
    rating: 3,
    email: "emma@example.com",
    phone: "9876543216",
    posts: 11,
    profilePicture: "/src/assets/user.svg",
  },
  {
    id: 9,
    name: "Liam Brown",
    status: "Active",
    rating: 4,
    email: "liam@example.com",
    phone: "9876543217",
    posts: 14,
    profilePicture: "/src/assets/user.svg",
  },
];
